# Generated by Django 2.0.2 on 2018-10-02 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Blog title', max_length=100),
        ),
    ]
